name: '🐛 Bug Report'
description: 'Create a report to help us improve.'
title: 'fix: '
labels: ['bug']

body:
  - type: textarea
    id: bug-description
    attributes:
      label: 'Describe the Bug'
      description: 'A clear and concise description of what the bug is. What happened? What did you see?'
      placeholder: "ex: When I click the 'Add to Cart' button, the page crashes."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 'Steps to Reproduce'
      description: 'Please provide detailed steps to reproduce the behavior.'
      placeholder: |
        1. Go to the 'Product Detail' page.
        2. Click on the 'Add to Cart' button.
        3. Scroll down to the bottom of the page.
        4. See the application crash with a 'TypeError'.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 'Expected Behavior'
      description: 'A clear and concise description of what you expected to happen.'
      placeholder: 'ex: The item should be added to the cart, and a success notification should appear.'
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain your problem. You can drag and drop images here.'
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: 'Operating System'
      description: 'What operating system are you using?'
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - macOS Sonoma
        - macOS Ventura
        - Linux
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: 'Browser'
      description: 'What browser are you using?'
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Brave
    validations:
      required: false