name: '✨ Feature Request'
description: 'Suggest an idea for this project.'
title: 'feat: '
labels: ['feature']

body:
  - type: textarea
    id: related-problem
    attributes:
      label: 'Is your feature request related to a problem?'
      description: 'A clear and concise description of what the problem is. Please describe the situation that the new feature would improve.'
      placeholder: "ex: I'm always frustrated when I have to manually sort the product list..."
    validations:
      required: true

  - type: textarea
    id: desired-solution
    attributes:
      label: "Describe the solution you'd like"
      description: 'A clear and concise description of what you want to happen.'
      placeholder: "ex: I would like a dropdown menu with 'Sort by Price' and 'Sort by Name' options."
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: 'ex: I also thought about adding filter buttons, but a dropdown seems cleaner.'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional Context'
      description: 'Add any other context, mockups, or screenshots about the feature request here.'
    validations:
      required: false